### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by Timonzimm** [orionsoft/graphql-compiler#1]
How would you make it work with a `@graphql` decorator? I just can't for the life of me figure out how to use this package with a simple example.

If I import the file like so:
`import get_user_data from '/imports/gql/get_user_data.graphql';`

And then:
`@graphql(get_user_data, {`

or even:
`import gql from 'graphql-tag';`
``@graphql(gql`${get_user_data}`, {``

It just doesn't work and pops an error in the console (filter of undefined).

Edit: the second technique works with a simple query, I probably have a syntax error.

**Comment by nicolaslopezj** [comment]
Mm try ```console.log(get_user_data)``` and check what are you importing

**Comment by Timonzimm** [comment]
Already did, it's exactly the `.graphql` file as a String, but doesn't get accepted by `@graphql`.

**Comment by nicolaslopezj** [comment]
I think this should work...

```js
@graphql(gql`${get_user_data}`, {
```

Maybe you have a syntax error in your .graphql file
